#####################################################
#          UChicago Data Science for Social Good:   #
#              Optimizing Waste Collection          #
#               from Portable Sanitation            #
#####################################################


#How to read the yaml file...
#meta:
#  loop_over_surface: ["implementation"] #When generating experiments, create an instance for every list product cross-section for the list in the implementation dict.
#  loop_over_deep: ["parameters"] #When generating experiments, create an instance for every cross-section in the flattened dict of dicts.

############################
# Database column names    #
############################

cols:
  toiletname: "ToiletName" #the name of the toilet / toilet identifier
  date: "Collection_Date" # date / date identifier
  feces: "FecesContainer_percent" #How full the container will be
  urine: "UrineContainer_percent"
  feces_collect: "" #Should the toilet be collected?
  urine_collect: ""
  #WASTE = {"feces": FECES, "urine": URINE} # Either feces or urine
  #COLLECT = {"feces": FECES_COLLECT, "urine": URINE_COLLECT}


############################
# Model parameters         #
############################
#model: ["LinearRegression", "RandomForest", "Autoregression", "SimpleModel"]
model: ["LinearRegression", "RandomForest", "Autoregression"]

parameters:
  RandomForest:
    n_estimators: [1, 10, 25, 50, 100]  # [1000, 10000]
    max_depth: [1, 3, 5, 10, 20]  # 50, 100
    max_features: ['sqrt', 'log2']  # [2, 4, 8, 16, "auto"]
    criterion: ['gini', 'entropy']
    min_samples_split: [2, 5, 10]
  Autoregression:
    maxlag: [5, 10]
  LinearRegression:
    dummy: [1] #A fake parameter making sure that we loop over this model.


#############################
# Implementation parameters #
#############################
implementation:
  loss: ["L2","L1"]
  prediction_horizon: [1] #How many days
  aggregation_measure: "mean" #A measure to use to aggregate the losses across different folds. Since different experiments may have different numbers of folds, should be a probability measure.
